en:
  languageName: English
  weight: 1

zh-hans:
  languageName: 简体中文
  weight: 4
  params:
    description: 只是一个博客（也许吧
    keywords: 'Falling_Studio'
    archive:
      dateFormat: 01-02
